baseURL = "http://dukeellington.org.uk"
languageCode = "en"
title = "DESUK: The Duke Ellington Society UK"
enableRobotsTXT = true

theme = "mainroad"


# Privacy
[youtube]
  privacyEnhanced = true

[permalinks]
  blog = "/:year/:month/:title/"

[Params]
  subtitle = "Nil significat nisi pulsatur"
  copyright = "DESUK"
  # TODO: description (not used anywhere?)
  readmore = true

  highlightColor = "#001ca0"

  twitter_cards = true

  # TOC off by default
  toc = false

  # TODO: Consider re-enabling this with an order that matches the menu
  post_navigation = false

  post_meta = ["date", "categories"]
  mainSections = ["post", "blog", "news"]
  dateformat = "2006-01-02" # change the format of dates

[menu]
  [[menu.side]]
    name = "The Duke Ellington Society Of Sweden"
    url = "https://ellington.se"
    weight = 1

  [[menu.side]]
    name = "The Jazz Centre UK"
    url = "http://thejazzcentreuk.co.uk"
    weight = 2

  [[menu.side]]
    name = "The Duke – Where and When"
    url = "http://tdwaw.ca"
    weight = 3

  [[menu.side]]
    name = "Ellington Live"
    url = "https://villesville.blogspot.com"
    weight = 4

[Params.sidebar]
  home = "right"
  list = "left"
  single = false

  # Enable widgets in given order
  widgets = ["recent", "sidemenu", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5 # Number of articles
  tags_counter = true # Show number of post with tags

[Params.widgets.social]
  # Enable parts of social widget
  facebook = "dukesocuk"
  twitter = "dukesocuk"
  # instagram = "username"
  # linkedin = "username"
  # telegram = "username"
  # github = "username"
  # gitlab = "username"
  # bitbucket = "username"
  email = "desuk@dukeellington.org.uk"

  # TODO: Make this work
  # discord = "https://discord.gg/efQNUMa"
