baseURL = "http://dukeellington.org.uk/sandbox"
languageCode = "en-GB"
title = "DESUK: The Duke Ellington Society UK"
enableRobotsTXT = true

theme = "mainroad"


# Privacy
[youtube]
  privacyEnhanced = true

[permalinks]
  blog = "/:year/:month/:title/"

[Params]
  subtitle = "Nil significat nisi pulsatur"
  copyright = "DESUK"
  # TODO: description (not used anywhere?)
  readmore = true

  twitter_cards = true

  # TOC off by default
  toc = false

  # TODO: Consider re-enabling this with an order that matches the menu
  post_navigation = false

  post_meta = ["date", "categories"]
  mainSections = ["post", "blog", "news"]
  dateformat = "2006-01-02" # change the format of dates

[[Params.blogroll]]
  name = "The Duke Ellington Society Of Sweden"
  url = "https://ellington.se"

[[Params.blogroll]]
  name = "The Jazz Centre UK"
  url = "http://thejazzcentreuk.co.uk"

[[Params.blogroll]]
  name = "ellingtonweb.ca"
  url = "http://ellingtonweb.ca"

[Params.sidebar]
  home = "right"
  list = "left"
  single = false

  # Enable widgets in given order
  widgets = ["recent", "blogroll", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5 # Number of articles
  tags_counter = true # Show number of post with tags

[Params.widgets.social]
  # Enable parts of social widget
  # facebook = "username"
  # twitter = "username"
  # instagram = "username"
  # linkedin = "username"
  # telegram = "username"
  # github = "username"
  # gitlab = "username"
  # bitbucket = "username"
  email = "desuk@dukeellington.org.uk"
